data work.projet;
    length sujet $30.;
    matiere = "histoire";
    duree = 30;
    sujet = "WWII";
    output;
    sujet = "4eme république";
    output;
    sujet = "5eme république";
    output;
run;
